"""Mask-edge and foreground-color refinement algorithms.

This module sits between matting and layer export. It uses the original image,
the soft alpha matte, and an inpainted background estimate to improve two things:

1. the region sent to the inpainting model; and
2. the foreground RGBA values around semi-transparent or flat-color edges.

All masks in this module have image resolution ``(height, width)``.
"""

import numpy as np

from .layerd_refine import (
    estimate_fg_alpha,
    estimate_fg_color,
    expand_mask,
    find_flat_color_region_ccs,
    shrink_mask_ratio,
)

# Avoid unstable foreground-color division where alpha is almost fully opaque.
_UNBLEND_ALPHA_CLIP = [0, 0.95]

# Retain colors that explain 99% of the pixels considered by palette extraction.
_PALETTE_PERCENTILE = 0.90

# A small palette is sufficient for UI-like objects and keeps refinement cheap.
_FG_REFINE_NUM_COLORS = 2

# Remove 10% of a connected component when identifying its inner boundary band.
_FG_REFINE_N_INNER_RATIO = 0.1


def build_inpaint_mask(
    image_rgb: np.ndarray,
    hard_mask: np.ndarray,
    kernel_size: tuple[int, int],
) -> np.ndarray:
    """Build the mask used to inpaint behind one component.

    The hard segmentation alone can miss anti-aliased pixels, shadows, or a
    uniform-color fringe. Flat-color regions are therefore combined with a
    slightly shrunken component interior, then the result is expanded to give
    the inpainting model enough surrounding context.

    Args:
        image_rgb: Original RGB image as a uint8-compatible array.
        hard_mask: Boolean segmentation mask for the current component.
        kernel_size: Morphology kernel derived from the image dimensions.

    Returns:
        A full-resolution mask covering pixels that should be reconstructed.
    """
    # Split the hard mask into connected components and find dominant flat-color
    # regions inside each component. Colors themselves are unused in this step.
    color_masks, _, components = find_flat_color_region_ccs(
        image_rgb,
        hard_mask,
        max_num_colors=_FG_REFINE_NUM_COLORS,
        percentile=_PALETTE_PERCENTILE,
    )

    # If palette analysis finds nothing useful, safely fall back to an expanded
    # version of the original segmentation mask.
    if not components:
        return expand_mask(hard_mask, kernel_size)

    # Preserve the complete component when it has no flat-color masks. Otherwise,
    # shrink its geometric core so the explicit color masks determine the edge.
    inner_components = [
        component
        if not color_masks[index]
        else shrink_mask_ratio(component, _FG_REFINE_N_INNER_RATIO)
        for index, component in enumerate(components)
    ]

    # Union component interiors with all detected color regions, then add context
    # around the union for smoother inpainting across the object boundary.
    combined = np.any(inner_components + sum(color_masks, []), axis=0)
    return expand_mask(combined, kernel_size)


def refine_alpha_with_colors(
    image_rgb: np.ndarray,
    background_rgb: np.ndarray,
    alpha: np.ndarray,
    hard_mask: np.ndarray,
    kernel_size: tuple[int, int],
) -> tuple[np.ndarray, np.ndarray]:
    """Recover foreground colors and improve alpha at component boundaries.

    A composited source pixel follows ``image = alpha * foreground +
    (1 - alpha) * background``. Given the source, a soft alpha estimate, and the
    inpainted background, this function first solves for foreground RGB. It then
    uses dominant component colors to recover missed or weak alpha pixels near
    flat-color edges.

    Returns:
        ``(refined_alpha, foreground_rgb)`` at the original image resolution.
    """
    # Normalize dtypes expected by the LayerD numerical helpers. The alpha copy
    # is intentionally mutated locally and returned to the caller.
    image_uint8 = image_rgb.astype(np.uint8)
    background_uint8 = background_rgb.astype(np.uint8)
    alpha = alpha.astype(np.float64)
    # Undo the original foreground/background composition using the temporary
    # background generated by the inpainting model.
    foreground_rgb = estimate_fg_color(
        image_uint8,
        background_uint8,
        alpha,
        _UNBLEND_ALPHA_CLIP,
    )

    # Analyze every connected component separately so colors from disconnected
    # objects do not influence one another.
    color_masks, colors, components = find_flat_color_region_ccs(
        image_uint8,
        hard_mask,
        max_num_colors=_FG_REFINE_NUM_COLORS,
        percentile=_PALETTE_PERCENTILE,
    )
    for component_colors, component_masks, component in zip(
        colors, color_masks, components
    ):
        # Accumulate the strongest alpha proposal and its corresponding color.
        # Coverage counts how many colors claim each pixel; multiple claims mark
        # a boundary as ambiguous and prevent an unsafe update there.
        refined_alpha = np.zeros_like(alpha)
        refined_color = np.zeros_like(foreground_rgb)
        coverage = np.zeros_like(alpha)

        for color, color_mask in zip(component_colors, component_masks):
            # Search just outside the detected flat-color region for pixels that
            # can be explained by this foreground color and the known background.
            expanded_color_mask = expand_mask(color_mask, kernel_size)
            candidate_alpha = estimate_fg_alpha(
                expanded_color_mask,
                color,
                background_uint8,
                image_uint8,
            )
            if candidate_alpha is None:
                continue
            refined_alpha = np.maximum(refined_alpha, candidate_alpha)
            refined_color[candidate_alpha > 0] = color
            coverage += (candidate_alpha > 0).astype(int)

        # This component produced no usable color-based alpha estimates.
        if refined_alpha.sum() == 0:
            continue

        ambiguous_boundary = coverage > 1

        # Subtract a shrunken component from itself to obtain its inner edge band.
        inner_boundary = (
            ~shrink_mask_ratio(component, _FG_REFINE_N_INNER_RATIO)
        ) & component

        # Only fill missing alpha or improve the inner edge, and never modify a
        # pixel for which several foreground colors provide competing answers.
        target = ((alpha == 0) | inner_boundary) & ~ambiguous_boundary
        alpha[target] = np.maximum(alpha[target], refined_alpha[target])

        # Keep foreground RGB consistent with pixels whose alpha was recovered
        # from a dominant flat color.
        update = target & (refined_alpha > 0)
        foreground_rgb[update] = refined_color[update]

    return alpha, foreground_rgb
